### ISSUE TITLE
Casts

### ISSUE THREAD

**Issue by flv92** [Omertron/api-themoviedb#13]
I just realized casts are not correctly read by the api. It searches for a "casts" json tag whereas the correct one is "credits"
"credits":{"cast":[{"id":65731,.......}], "crew":[{},{}....]}

Thanks for reading and hope you'll fix it ;)

**Comment by Omertron** [comment]
I have updated the master branch with the new code. 
This has all the current methods of themoviedb in there but does need a little more tidy up before I release an official version
