### ISSUE TITLE
List<Artwork> getImages() throws NullPointerException

### ISSUE THREAD

**Issue by Nikitenko** [Omertron/api-themoviedb#22]
I try to get MovieInfo:
theMovieDbApi.getMovieInfo(suggestion.getId(), "ru");
movieInfo.getOriginalTitle(), movieInfo.getGenres() and etc. returns correct results 
movieInfo.getImages() throws NullPointerException

**Comment by Omertron** [comment]
What version is this with?

**Comment by Omertron** [comment]
Should be fixed with the latest commit

**Comment by Nikitenko** [comment]
Thank you, NullPointerException fixed, but getImages() always empty and not available for TVInfo

**Comment by Omertron** [comment]
Yes, there are no images provided with the default call of the getMovieInfo(), you have to either use the getMovieImages() method or use the "appendToResponse" to get them (but see issue #23 )

I am just working on implementing the #23 so that may not work until the final release of 4.0
