### ISSUE TITLE
Model Series TV

### ISSUE THREAD

**Issue by Miloune** [Omertron/api-themoviedb#27]
Hello,

I think i found a little bug.
When you call theses methods:
 * getTVPopular
 * getTVTopRated
 * getTVOnTheAir
 * getTVAiringToday

The return list will be TVInfo and not TVBasic.

At this moment, we can't get serie overview like in this example: http://docs.themoviedb.apiary.io/reference/tv/tvpopular/get

Hope you understand me :)

PS: I'm using Maven

**Comment by Miloune** [comment]
UP :)

**Comment by Omertron** [comment]
Thanks, I will look at this
