### ISSUE TITLE
Caching of Media

### ISSUE THREAD

**Issue by bwestpha** [Omertron/api-themoviedb#29]
Hey there,
it would be really really nice if there was an built in solution for caching results, especially the media files behind the results (for example images!). They are quite large and always have to be re-loaded if a new API call is done (as far as I can see that).

Maybe this would be a nice feature!

thanks in advance. ben

**Comment by Omertron** [comment]
Hi Ben,

I think that is the job of the application that is using the API to cache the images that they feel they are going to need to reuse.
