### ISSUE TITLE
API Noob with a question

### ISSUE THREAD

**Issue by OmniWan** [Omertron/api-themoviedb#30]
Sorry if this is a dumb question but I'm new to using Android Studio... How exactly do we use this wrapper and include it in my android studio project? I tried bringing in the files to my project, and but when I tried to run code from http://docs.themoviedb.apiary.io/#reference/movies/movieid/get, I just got a bunch of errors and non-existant imports. How do we use your wrapper in Android Studio project?

**Comment by SN23** [comment]
You have to import it into the project by click build-> Edit Libraries and dependencies. Then click the + sign and click library dependency and paste this in com.omertron:themoviedbapi:4.0.
