### ISSUE TITLE
Not getting return values for run time and overview

### ISSUE THREAD

**Issue by SN23** [Omertron/api-themoviedb#33]
On certain values of the movies I get 0 null. for overview I get null and for run time I get zero. But I am able to get other values such as the  release date, revenue, budget and the poster path.

**Comment by Omertron** [comment]
Can you explain a little more? Give an example of a movie where this is working and one that is not.

**Comment by SN23** [comment]
The overview is null and run time is 0 for all movies I search for. Below are a few examples
![image](https://cloud.githubusercontent.com/assets/9086766/13268578/4bad92a2-da51-11e5-985c-1d2e00b2a919.png)

![image](https://cloud.githubusercontent.com/assets/9086766/13268613/7ae7e6b2-da51-11e5-9b85-5114b65ee87b.png)

![image](https://cloud.githubusercontent.com/assets/9086766/13268739/3440c908-da52-11e5-8dbd-9c27d75711ba.png)

**Comment by Omertron** [comment]
What version of the API are you using?

[20:55:50   INFO] com.omertron.themoviedbapi.DebugTest newTest - Title     : Deadpool 
[20:55:50   INFO] com.omertron.themoviedbapi.DebugTest newTest - Release   : 2016-02-09 
[20:55:50   INFO] com.omertron.themoviedbapi.DebugTest newTest - Overview  : Based upon Marvel Comics’ most unconventional anti-hero, DEADPOOL tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life. 
[20:55:50   INFO] com.omertron.themoviedbapi.DebugTest newTest - Run Time  : 108

**Comment by SN23** [comment]
I am using version 4.1 which I downloaded from http://mvnrepository.com/artifact/com.omertron/themoviedbapi/4.1

**Comment by Omertron** [comment]
If you are using maven, please try 4.2-SNAPSHOT

**Comment by SN23** [comment]
I'm using netbeans and just used the mvnrepository to get the jar file for the API. Where can I get the 4.2 snapshot jar file?

**Comment by Omertron** [comment]
If you have a pom.xml file, you can add it in there using

```
            <dependency>
                <groupId>com.omertron</groupId>
                <artifactId>themoviedbapi</artifactId>
                <version>4.2-SNAPSHOT</version>
                <type>jar</type>
            </dependency>
```

if not, can you post the code you are using and I can see if I can spot what is wrong

**Comment by Omertron** [comment]
I've released v4.2, so you can download that at your local repository of choice

**Comment by SN23** [comment]
Here is the code i am having problems with

`

        ResultList<MediaBasic> resultList = tmdb.searchMulti(movieTitle, counter, "en", Boolean.TRUE);
        List<MediaBasic> list = resultList.getResults();

        for(int i =0; i<list.size();i++)
        {
            if(list.get(i).getMediaType().toString().equalsIgnoreCase("Movie"))
            {
                MVB = (MovieBasic) list.get(i);
                String title = MVB.getTitle();
                String releaseDate = MVB.getReleaseDate();
                int id = MVB.getId();
                MovieInfo movieInfo = tmdb.getMovieInfo(id, apiKey, args);
                long budget = movieInfo.getBudget();
                long revenue = movieInfo.getRevenue();
                String overview = movieInfo.getOverview();
                int runTime = movieInfo.getRuntime();
                String posterPath = movieInfo.getPosterPath();
                String backdrop = movieInfo.getBackdropPath();
              
        
                System.out.println("------------------------MOVIE INFO------------------------");               
                System.out.println("Title: " + title);
                System.out.println("Release Date: " + movie.getReleaseDate());
                System.out.println("Budget $" + NumberFormat.getInstance().format(movie.getBudget()));
                System.out.println("Revenue $" + NumberFormat.getInstance().format(movie.getRevenue()));
                System.out.println("Overview: " + movie.getOverview());
                System.out.println("Run Time: " + movie.getRunTime());
                System.out.println("Poster Path " + "https://image.tmdb.org/t/p/w185" + posterPath);
                System.out.println();
            }
        }`

**Comment by Omertron** [comment]
This is the problem: `MovieInfo movieInfo = tmdb.getMovieInfo(id, apiKey, args);`

You are passing in the apiKey instead of the language.
