### ISSUE TITLE
Project documentation is not up-to-date

### ISSUE THREAD

**Issue by Phil795** [Omertron/api-themoviedb#39]
Hello Omertron,

firstly thanks a lot for this powerful api!

But I have some trouble with the documentation. Please can you update the docs? 

I need a way to get the externalIds. I tried it with a `.getTvSeasons().getSeason(ID, 1, "de-DE")` but the externalId section is empty.

**Comment by Phil795** [comment]
Is this API still supported?

**Comment by Omertron** [comment]
Hi Phil,

Yes, I have been busy with other things though and don't seem to have github setup to email me with new issues...

Anyway, are you sure there are external IDs for that ID?

Can you provide a code snippet of the command so I can try it out?

**Comment by Phil795** [comment]
Hi Omertron,

meanwhile I moved to the api from holger brandl. 

But I solved the problem. I forgot to add "external_ids" as append_to_response.

**Comment by Omertron** [comment]
Ok, thanks for closing the issue
