### ISSUE TITLE
How do i get the ShowId from TvEpisodeInfo?

### ISSUE THREAD

**Issue by CraigNavin** [Omertron/api-themoviedb#45]
I am trying to use the ShowId property from the TvEpisodeInfo class but it is null each time I try to use it. Here is the toString() of the class that i have just created. ShowId bolded. 
> TVEpisodeInfo[credits=MediaCreditList[cast=[],crew=[],guestStars=[],id=0],crew=[],externalIDs=ExternalID[freebaseId=null,freebaseMid=null,id=0,imdbId=null,tvdbId=null,tvrageId=null],guestStars=[],images=[],methods=[],productionCode=null,videos=[],airDate=2018-02-02,episodeNumber=10,name=The Killers,overview=As a cornered Kovacs braces for a final showdown in the sky, a new hero emerges and more buried secrets come to light.,seasonNumber=1,**showId=null**,stillPath=/6rs8oCBfY7ohnhPjOEYT3dnMrUf.jpg,backdropPath=null,id=1402150,mediaType=EPISODE,popularity=0.0,posterPath=null,voteAverage=8.0,voteCount=4]

Here is the code I am using to get the result
`info = api!!.getEpisodeInfo(TVid!!,seasonNum!!,epNum!!,"en")`

I have tried this will multiple different shows and all are the same.

**Comment by Omertron** [comment]
Hi, can you provide some examples of the IDs, season/ep numbers you're using?

**Comment by CraigNavin** [comment]
TvID = 67178
season number  = 1
All of the episodes do not have a showId value. 
After looking on the official API and testing with these numbers, the response does not have a showId property.

**Comment by Omertron** [comment]
Hi,

Yes, I have checked and that's not available with the episode info (even with the append to response), so your best bet is to fire a TVSeries request too.
