### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by MihutescuDenis** [Omertron/api-themoviedb#51]
I know there is documentation, but I don't understand how I can use it. How can I get the data about a movie, how can I store it and how can I display it for example in the console. A piece of basic code would help me. In which a movie is created, the data for it is obtained. And how can I get more movies. (list). And how to search for a movie by name.
I have an api key.

**Comment by Omertron** [comment]
The API (amongst others) is used in this project: https://github.com/YAMJ/yamj-v2
Specifically here: https://github.com/YAMJ/yamj-v2/blob/master/yamj/src/main/java/com/moviejukebox/plugin/TheMovieDbPlugin.java

It doesn't answer your question, but perhaps shows you how it can be used.
